apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.rtxtvremote'
version = '1.0.0'

android {
  namespace "expo.modules.rtxtvremote"
  defaultConfig {
    minSdkVersion getMinSdkVersionFromExpoModuleConfig()
    targetSdkVersion getTargetSdkVersionFromExpoModuleConfig()
  }
}
